#!/usr/bin/env python3
"""Generates the save state field visitors.

Hand-maintaining a list of ~600 members is how save states rot: someone adds
a field, forgets the list, and states break subtly months later. The list is
generated from the declarations instead, and regenerating is a diff.

Each class gets one visit_state() used by both the writer and the reader, so
a field can never be saved but not loaded.
"""
import re
import sys
from pathlib import Path

# type name_{...};  |  type name_ = ...;  |  type name_;
MEMBER = re.compile(
    r'^\s{4}(?!return|using|static_assert)'
    r'(?P<type>(?:const\s+)?[A-Za-z_][\w:]*'
    r'(?:\s*<[^;]*?>)?(?:\s*\*)?)\s+'
    r'(?P<name>[a-z_][\w]*_?)\s*'
    r'(?:\{[^;]*\}|=\s*[^;]*)?\s*;\s*(?://.*)?$')

SKIP_TYPES = ('void', 'return')


def members(text: str, start: int, end: int) -> list[tuple[str, str]]:
    # Declarations are joined onto one logical line first: a member whose
    # initialiser wraps (std::vector<std::uint8_t> superfx_ram =\n ...) would
    # otherwise be dropped silently, which is precisely the failure this
    # generator exists to prevent.
    found = []
    pending = ''
    for line in text.splitlines()[start - 1:end]:
        if not line.strip() or line.strip().startswith('//'):
            pending = ''
            continue
        pending = (pending + ' ' + line.strip()) if pending else line
        if not pending.rstrip().endswith(';'):
            if pending.count('{') != pending.count('}'):
                pending = ''
            continue
        line, pending = pending, ''
        match = MEMBER.match(line)
        if not match:
            continue
        type_name = match.group('type').strip()
        name = match.group('name')
        if type_name in SKIP_TYPES or name.endswith('()'):
            continue
        found.append((type_name, name))
    return found


def emit(name: str, fields: list[tuple[str, str]], skip: set[str]) -> str:
    lines = [f'// Generated by tools/generate_state_visitors.py for {name}.',
             '// Do not edit by hand; re-run the generator instead.']
    for type_name, field in fields:
        if field in skip:
            lines.append(f'// {field}: excluded, see the visitor call site.')
        else:
            lines.append(f'visitor({field});')
    return '\n'.join(lines) + '\n'


def class_body(text: str, name: str) -> tuple[int, int]:
    """Line range of a class body, found by name rather than by line number.

    Hardcoded ranges silently drift the moment anything above them is edited,
    and a member that drifts out of range is a member that stops being saved.
    """
    start = None
    for index, line in enumerate(text.splitlines(), start=1):
        if re.match(rf'^\s*(class|struct)\s+{re.escape(name)}\b', line):
            start = index
            break
    if start is None:
        raise SystemExit(f'class {name} not found in the source')
    depth = 0
    for index, line in enumerate(text.splitlines()[start - 1:], start=start):
        depth += line.count('{') - line.count('}')
        if depth == 0 and index > start:
            return start, index
    raise SystemExit(f'class {name} body is unterminated')


if __name__ == '__main__':
    path, class_name, out = sys.argv[1:4]
    skip = set(sys.argv[4:])
    text = Path(path).read_text()
    start, end = class_body(text, class_name)
    fields = members(text, start, end)
    names = {name for _, name in fields}
    missing = skip - names
    if missing:
        raise SystemExit(
            f'{class_name}: excluded members not found: {sorted(missing)}')
    Path(out).write_text(emit(class_name, fields, skip))
    print(f'{class_name}: {len(fields)} members '
          f'({len(fields) - len(skip)} saved, {len(skip)} excluded) -> {out}')
